version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: pesonal-mangager-api
    ports:
      - "9001:9000"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n, -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.17.0.1:5440/personal_manager?currentSchema=public
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db-postgres

  db-postgres:
    image: postgres:latest
    container_name: db-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5440:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
    external: true