version: "3"

networks:
  app-network:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus-config:/prometheus-config
      - ./data/prometheus:/prometheus
    command: 
      - '--config.file=/prometheus-config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - '9090:9090'
    user: root
    networks:
      - app-network

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - '9100:9100'      
    networks:
      - app-network


  grafana:
    image: grafana/grafana
    expose:
      - 3000
    ports:
      - '3000:3000'
    networks:
      - app-network
    user: '472'
    depends_on:
      - prometheus


