global:
  scrape_interval: 15s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']

- job_name: personal_manager_client
  static_configs:
    - targets:
      - nginx:80 

- job_name: personal_manager_api
  metrics_path: '/actuator/prometheus'
  static_configs:
      - targets:
        - 192.168.0.18:9000
        
- job_name: 'node_exporter'
  metrics_path: /metrics  
  scrape_interval: 10s
  static_configs:
    - targets: ['nodeexporter:9100']

