name: CI/CD GSC

on:
  push:
    branches: [ homologacao ]

jobs:
  test:
    name: Execute Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 11.0.4
          distribution: 'adopt'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
        
  docker:
    name: Build and Publish docker image
    runs-on: ubuntu-20.04
    needs: [test]
    env:
     REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $REPO:api-homologacao:$(date +%s)
      - name: Publish Docker image
        run: docker push $REPO
        
          

